### ISSUE TITLE
Unable to identify network on iOS

### ISSUE THREAD

**Issue by Angelo029** [vinayakkulkarni/vue-identify-network#283]
Everything is working fine on android os, but on iOS, it is always unable to identify network. Anyone encountered this issue on iOS? If you encountered this, how did you resolve this? Advance thank you for the help :D

Device used:
iPhone 6 v12.4.8

**Comment by halaszbalazs** [comment]
Just ran into the same issue and after some research I ended up with making AJAX requests and calculating the time for the response as this component checks if the navigator vendor name contains Google or not (see this snippet: https://github.com/vinayakkulkarni/vue-identify-network/blob/6804939f440834de519c6e6830abfe11931701b4/src/VueIdentifyNetwork.vue#L40).

If the navigator vendor does not contain "Google" then it returns with unknown network details, I guess thats because iOS Safari and Safari in all does not implemented navigator.connection which the component relies on.

**Comment by vinayakkulkarni** [comment]
That's cause `downlink` isn't supported out-of-the-box by iOS – https://caniuse.com/mdn-api_networkinformation_downlink
